### ISSUE TITLE
Class name

### ISSUE THREAD

**Issue by JohannesBetz** [michaelfeil/commonroad_motionplaner_michaelf#1]
In deiner Anleitung erwähnst du, dass man deinen Code einfach mit dem Student_EXAMPLE ersetzen kann, die klasse für deinen motion planner heißt allerdings 
	**class StudentMotionPlanner(GreedyBestFirstSearch):**

Damit man es direkt mit dem Example ersetzen und auch ohne größere Umstellungen starten kann, wäre folgender Class-Name besser:
	**class StudentMotionPlannerExample(GreedyBestFirstSearch):**

Alternativ kannst du auch einfach in deiner Anleitung erwähnen, dass man nicht das example sondern das STUDENT.py file ersetzt, dann passt es auch ;)

**Comment by michaelfeil** [comment]
Danke Johannes für die genaue Beschreibung. Ich habe den Hinweis zu STUDENT.py geändert. Um mit den zukünftigen Versionen des Commonroad Search Repos funktionsfähig zu bleiben, wäre es sinnvoll nur die klassen wie 
`class optimal_route_planned()` oder die Klassenfunktion `distance_to_goal()` von `StudentMotionPlanner(GreedyBestFirstSearch) ` bei Bedarf zu  übernehmen.
