### ISSUE TITLE
The Planner Should be able to solve simple scenarios

### ISSUE THREAD

**Issue by alessiogambi** [michaelfeil/commonroad_motionplaner_michaelf#2]
Dear @michaelfeil , I got to know this repo thanks to Edmond @ TUM [1].

I am trying to use available planners as test subjects to benchmark test generations and currently investigating the feasibility of using commonroad. Unfortunately (you can read more at [1]), I was not able to have any planner work with basic scenarios. They work for a straight road but fail soon when there's any turn.

Since I haven't figured out yet whether the issue is in how I generate the scenarios or in the planner itself, maybe you can take a look at those scenarios [2][3][4][5] and tell me if you spot something wrong? For example, if you run your planner on them, can it find a solution? Which motion primitives did you use?

Best
-- Alessio

[1] https://commonroad.in.tum.de/forum/t/cannot-find-a-plan-to-solve-a-simple-scenario/628/13?u=alessiogambi
[2] 90-turn https://pastebin.com/wBewxRA2
[2] 90-turn with [-3.13,3.13] as goal orientation https://pastebin.com/6FtP341B
[3] 45-turn https://pastebin.com/N84VFZ8N
[4] 30-turn https://pastebin.com/SdCaNwZS

**Comment by michaelfeil** [comment]
Thanks for your request, I responded to it in the commonroad forum and will close it here.
